### PR TITLE
Issue13-Unit Testing

### PR DESCRIPTION
**Pull request by ArCiGoUnoSquare**
* Some constants in `Grid.spec.js` were removed and placed into files to make the file more readable
* Was added a unit test to check the top pager

### CODE REVIEW

**Comment by kadosh** [comment]
Conflicts

**Comment by ArCiGoUnoSquare** [comment]
I'm fixing that

**Comment by geoperez** [comment]
:|

**Comment by kadosh** [comment]
Branch was previously merged and removed. Please open a new issue and branch to do any further changes.

**Comment by ArCiGoUnoSquare** [comment]
Working on that

**Pull request closed without merging**
