### PR TITLE
Master Detail

### PR DESCRIPTION
**Pull request by AlexisDragneel**
The PR is going to be open in order to request review of this new feature

### CODE REVIEW

**Comment by geoperez** [comment]
Please fix the lint issues.

**Comment by kadosh** [comment]
Can you please add an example on how this must be implemented?

**Comment by geoperez** [comment]
@AlexisDragneel I miss you!

**Comment by geoperez** [comment]
Can you fix the lint, please?

**Comment by geoperez** [comment]
Can you retest? I did some changes to match master branch.

**Pull request merged**
