### PR TITLE
Fix enter key crash in filters

### PR DESCRIPTION
**Pull request by nickpalmer**
* Make sure that onEnter handler is defined before attempting to call it
* Pass onApplyClick down to the TextArea key handler

### CODE REVIEW

**Comment by geoperez** [comment]
Thanks for the heads up! @kadosh  can you review?

Also, remember me to fix the CI.

**Comment by kadosh** [comment]
Thank you @nickpalmer

**Comment by nickpalmer** [comment]
Did you mean to close this without merging?

**Comment by kadosh** [comment]
My bad, sorry

**Pull request merged**
